/****************************************************************************
 *
 *   Copyright (c) 2020 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/**
 * @file RotorGeometry.hpp
 *
 * Rotor geometry definitions and effectiveness matrix computation.
 * Extracted from PX4's ActuatorEffectivenessRotors — standalone, no PX4 dependencies.
 *
 * The computeEffectivenessMatrix() function is a direct copy of the static method
 * from ActuatorEffectivenessRotors.cpp.
 */

#pragma once

#include <cfloat>
#include <matrix/matrix/math.hpp>
#include "ActuatorEffectiveness.hpp"

namespace px4_extraction {

static constexpr int NUM_ROTORS_MAX = 12;

struct RotorGeometry {
	matrix::Vector3f position;     ///< Rotor position in body frame [m]
	matrix::Vector3f axis;         ///< Thrust axis direction (normalized, e.g. {0,0,-1} for upward)
	float thrust_coef{1.0f};      ///< Thrust coefficient (CT), positive = thrust along axis
	float moment_ratio{0.05f};    ///< Yaw torque / thrust ratio (KM), sign determines CW/CCW
};

struct Geometry {
	RotorGeometry rotors[NUM_ROTORS_MAX];
	int num_rotors{0};
	bool propeller_torque_disabled{false};
	bool yaw_by_differential_thrust_disabled{false};
	bool propeller_torque_disabled_non_upwards{false};
	bool three_dimensional_thrust_disabled{false};
};

/**
 * Compute the 6×N effectiveness matrix from rotor geometry.
 * Verbatim copy of PX4's ActuatorEffectivenessRotors::computeEffectivenessMatrix()
 *
 * Rows: [roll_torque, pitch_torque, yaw_torque, thrust_x, thrust_y, thrust_z]
 * Columns: one per rotor
 *
 * @param geometry           Rotor geometry (positions, axes, CT, KM)
 * @param effectiveness      Output 6×16 matrix (columns filled starting at actuator_start_index)
 * @param actuator_start_index  Column offset (default 0)
 * @return Number of actuators added
 */
inline int computeEffectivenessMatrix(const Geometry &geometry,
				      ActuatorEffectiveness::EffectivenessMatrix &effectiveness,
				      int actuator_start_index = 0)
{
	using namespace matrix;

	int num_actuators = 0;

	for (int i = 0; i < geometry.num_rotors; i++) {

		if (i + actuator_start_index >= ActuatorEffectiveness::NUM_ACTUATORS) {
			break;
		}

		++num_actuators;

		// Get rotor axis
		Vector3f axis = geometry.rotors[i].axis;

		// Normalize axis
		float axis_norm = axis.norm();

		if (axis_norm > FLT_EPSILON) {
			axis /= axis_norm;

		} else {
			// Bad axis definition, ignore this rotor
			continue;
		}

		// Get rotor position
		const Vector3f &position = geometry.rotors[i].position;

		// Get coefficients
		float ct = geometry.rotors[i].thrust_coef;
		float km = geometry.rotors[i].moment_ratio;

		if (geometry.propeller_torque_disabled) {
			km = 0.f;
		}

		if (geometry.propeller_torque_disabled_non_upwards) {
			bool upwards = fabsf(axis(0)) < 0.1f && fabsf(axis(1)) < 0.1f && axis(2) < -0.5f;

			if (!upwards) {
				km = 0.f;
			}
		}

		if (fabsf(ct) < FLT_EPSILON) {
			continue;
		}

		// Compute thrust generated by this rotor
		matrix::Vector3f thrust = ct * axis;

		// Compute moment generated by this rotor
		matrix::Vector3f moment = ct * position.cross(axis) - ct * km * axis;

		// Fill corresponding items in effectiveness matrix
		for (size_t j = 0; j < 3; j++) {
			effectiveness(j, i + actuator_start_index) = moment(j);
			effectiveness(j + 3, i + actuator_start_index) = thrust(j);
		}

		if (geometry.yaw_by_differential_thrust_disabled) {
			effectiveness(2, i + actuator_start_index) = 0.f;
		}

		if (geometry.three_dimensional_thrust_disabled) {
			effectiveness(0 + 3, i + actuator_start_index) = 0.f;
			effectiveness(1 + 3, i + actuator_start_index) = 0.f;
			effectiveness(2 + 3, i + actuator_start_index) = -ct;
		}
	}

	return num_actuators;
}

/**
 * Create a standard Iris quadrotor X geometry.
 * Matches PX4's 10015_gazebo-classic_iris airframe definition.
 *
 * Motor layout (PX4 convention, top view, X forward):
 *   Motor 0 (FR, CCW): PX=+0.1515, PY=+0.245,   KM=+0.05
 *   Motor 1 (BL, CCW): PX=-0.1515, PY=-0.1875,  KM=+0.05
 *   Motor 2 (FL, CW):  PX=+0.1515, PY=-0.245,   KM=-0.05
 *   Motor 3 (BR, CW):  PX=-0.1515, PY=+0.1875,  KM=-0.05
 *
 * All axes: {0, 0, -1} (upward thrust in NED)
 * All CT: 1.0
 */
inline Geometry createQuadXIris()
{
	Geometry geom{};
	geom.num_rotors = 4;

	const matrix::Vector3f axis_up{0.f, 0.f, -1.f};

	// Motor 0: Front-Right, CCW
	geom.rotors[0].position = {0.1515f, 0.245f, 0.f};
	geom.rotors[0].axis = axis_up;
	geom.rotors[0].thrust_coef = 1.0f;
	geom.rotors[0].moment_ratio = 0.05f;

	// Motor 1: Back-Left, CCW
	geom.rotors[1].position = {-0.1515f, -0.1875f, 0.f};
	geom.rotors[1].axis = axis_up;
	geom.rotors[1].thrust_coef = 1.0f;
	geom.rotors[1].moment_ratio = 0.05f;

	// Motor 2: Front-Left, CW
	geom.rotors[2].position = {0.1515f, -0.245f, 0.f};
	geom.rotors[2].axis = axis_up;
	geom.rotors[2].thrust_coef = 1.0f;
	geom.rotors[2].moment_ratio = -0.05f;

	// Motor 3: Back-Right, CW
	geom.rotors[3].position = {-0.1515f, 0.1875f, 0.f};
	geom.rotors[3].axis = axis_up;
	geom.rotors[3].thrust_coef = 1.0f;
	geom.rotors[3].moment_ratio = -0.05f;

	return geom;
}

/**
 * Create a generic quadrotor X geometry with unit arm lengths.
 * Simpler geometry for quick testing: positions at (±1, ±1, 0).
 */
inline Geometry createQuadXGeneric()
{
	Geometry geom{};
	geom.num_rotors = 4;

	const matrix::Vector3f axis_up{0.f, 0.f, -1.f};

	// Motor 0: Front-Right, CCW
	geom.rotors[0].position = {1.0f, 1.0f, 0.f};
	geom.rotors[0].axis = axis_up;
	geom.rotors[0].thrust_coef = 1.0f;
	geom.rotors[0].moment_ratio = 0.05f;

	// Motor 1: Back-Left, CCW
	geom.rotors[1].position = {-1.0f, -1.0f, 0.f};
	geom.rotors[1].axis = axis_up;
	geom.rotors[1].thrust_coef = 1.0f;
	geom.rotors[1].moment_ratio = 0.05f;

	// Motor 2: Front-Left, CW
	geom.rotors[2].position = {1.0f, -1.0f, 0.f};
	geom.rotors[2].axis = axis_up;
	geom.rotors[2].thrust_coef = 1.0f;
	geom.rotors[2].moment_ratio = -0.05f;

	// Motor 3: Back-Right, CW
	geom.rotors[3].position = {-1.0f, 1.0f, 0.f};
	geom.rotors[3].axis = axis_up;
	geom.rotors[3].thrust_coef = 1.0f;
	geom.rotors[3].moment_ratio = -0.05f;

	return geom;
}

} // namespace px4_extraction
